# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade cython
          pip3 install --user --upgrade requests

          sudo apt-get update
          sudo apt-get install build-essential libstdc++6 aidl libltdl-dev gettext

      - name: Build
        run: |
          buildozer appclean
          buildozer -v android debug
          zip movieGuess.zip bin/movieGuess-0.1-arm64-v8a_armeabi-v7a-debug.apk

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: 0.0.${{ github.run_id }}
          tag_name: 0.0.${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./movieGuess.zip
          asset_name: movieGuess.zip
          asset_content_type: application/zip