# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer
        run: pip3 install --user --upgrade buildozer

      - name: Configure Buildozer
        run: buildozer init

      - name: Build
        run: buildozer -v android debug
