# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer
        run: pip3 install --user --upgrade buildozer

      - name: Configure Buildozer
        run: | 
          buildozer init
          sed -i "s|title = My Application|title = Movie Guesser|" buildozer.spec
          sed -i "s|package.name = myapp|package.name = movieGuess|" buildozer.spec
          sed -i "s|package.domain = org.test|package.domain = movieGuess|" buildozer.spec

      - name: Build
        run: buildozer -v android debug
