# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade cython

          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install libstdc++6
          sudo apt-get install aidl 
          sudo apt-get install libltdl-dev

      - name: Configure Buildozer
        run: | 
          buildozer init
          sed -i "s|title = My Application|title = Movie Guesser|" buildozer.spec
          sed -i "s|package.name = myapp|package.name = movieGuess|" buildozer.spec
          sed -i "s|package.domain = org.test|package.domain = movieGuess|" buildozer.spec
          sed -i "s|# android.skip_update = False|android.skip_update = False|" buildozer.spec
          sed -i "s|# android.accept_sdk_license = False|android.accept_sdk_license = True|" buildozer.spec

      - name: Build
        run: buildozer -v android debug
